apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: wines-rag
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - wines-rag
  endpoints:
    - port: http
      path: /metrics
      interval: 10s