apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wines-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: backend
          image: ghcr.io/heilagrfox/wine-shop-devops/wines_rag_backend:75278820043eaf0599da0f4e417d0c4fe91a809a
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: HF_HOME
              value: "/app/.cache/huggingface"
            - name: FASTEMBED_CACHE_PATH
              value: "/app/.cache/fastembed"
          resources:
            requests:
              cpu: 500m
              memory: 1028Mi
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wines-rag
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
  template:
    spec:
      containers: []
