apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wines-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/heilagrfox/wine-shop-devops/wines_rag_backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: app-secrets
        env:
        - name: HF_HOME
          value: "/app/.cache/huggingface"
        - name: FASTEMBED_CACHE_PATH
          value: "/app/.cache/fastembed"
        resources:
          requests:
            cpu: 500m
            memory: 1028Mi
      imagePullSecrets:       
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wines-rag
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: LoadBalancer

