apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wines-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/heilagrfox/wine-shop-devops/wines-rag-frontend:86b4937b5f3767956d830bdb0214f15b29650b59
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_HOST
              value: "http://backend:8000"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wines-rag
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
  template:
    spec:
      containers: []
